name: bedrock
channels: !!python/tuple
- defaults
dependencies:
- click=6.6=py35_0
- flask=0.11.1=py35_0
- itsdangerous=0.24=py35_0
- jinja2=2.8=py35_1
- markupsafe=0.23=py35_2
- openssl=1.0.2h=2
- pip=8.1.2=py35_0
- python=3.5.2=0
- readline=6.2=2
- setuptools=27.2.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- werkzeug=0.11.11=py35_0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - aniso8601==1.1.0
  - arrow==0.8.0
  - brewer2mpl==1.4.1
  - cython==0.24.1
  - decorator==4.0.10
  - django==1.10.1
  - feedparser==5.2.1
  - flask-cors==3.0.2
  - flask-login==0.3.2
  - flask-restful==0.3.5
  - flask-restplus==0.4.0
  - folium==0.2.1
  - geocoder==1.17.4
  - markdown==2.6.6
  - nose==1.3.7
  - numpy==1.11.1
  - oauthlib==2.0.0
  - pandas==0.18.1
  - parsedatetime==2.1
  - passlib==1.6.5
  - pymongo==3.3.0
  - python-dateutil==2.5.3
  - pytz==2016.6.1
  - ratelim==0.1.6
  - requests==2.11.1
  - requests-oauthlib==0.6.2
  - scikit-learn==0.17.1
  - six==1.10.0
  - tweepy==3.5.0
  - vincent==0.4.4
  - xlrd==1.0.0
